name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test for LLVM ${{ matrix.llvm }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        llvm:
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install LLVM ${{ matrix.llvm }}
        run: curl https://apt.llvm.org/llvm.sh | sudo bash  -s -- ${{ matrix.llvm }}

      - name: Install Polly ${{ matrix.llvm }}
        run: sudo apt-get install -y libpolly-${{ matrix.llvm }}-dev
        if: matrix.llvm >= 14

      - name: Install zstd
        run: sudo apt-get install -y libzstd-dev
        if: matrix.llvm >= 16

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build Debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          # LLVM 11 doesn't work with -strict, see #53
          args: ${{ matrix.llvm == '11' && format('--features=llvm-{0}', matrix.llvm) || format('--features=llvm-{0}-strict', matrix.llvm) }}

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          # LLVM 11 doesn't work with -strict, see #53
          args: ${{ matrix.llvm == '11' && format('--release --features=llvm-{0}', matrix.llvm) || format('--release --features=llvm-{0}-strict', matrix.llvm) }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --features=llvm-${{ matrix.llvm }}-strict
